[package]
name = "paperplane-types"
version = "1.6.4"
authors = ["syn <isaqtm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde-aux = "0.6"
